osx_image: xcode8
language: objective-c
before_install: 
  - bundle install
script: 
  - xcodebuild build -project IBAnimatable.xcodeproj -scheme IBAnimatableApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest'
  - bundle exec danger